apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartpra-fin-service-deployment
  labels:
    app: system
spec:
  selector:
    matchLabels:
      app: system
  template:
    metadata:
      labels:
        app: system
    spec:
      containers:
      - name: smartpra-fin-service-deployment
        image: smartpra.azurecr.io/smartpra-fin-service:v1.0.2
        ports:
        - containerPort: 8082
      imagePullSecrets:
      - name: smartprasecret
      