server:
  port: 8082 
  servlet:
    context-path: /financial-service
spring:
  application:
    name: financial-service
  datasource:
    url: jdbc:sqlserver://SINAZEDEV17;instanceName=SmartPRA_DEV;portNumber=1433;user=devsmartpra;password=Rtsneftimp@423!#
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver   
  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: SmartPRAMaster
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        
    hibernate:
      ddl-auto: none
      
     
